name: twitter
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.12
  firebase_core: ^2.14.0
  font_awesome_flutter: ^10.5.0
  firebase_auth: ^4.6.3
  get_it: ^7.6.0
  provider: ^6.0.5
  cloud_firestore: ^4.8.1
  anim_search_app_bar: ^1.0.3
  image_picker: ^1.0.0
  firebase_storage: ^11.2.4
  intl: ^0.18.0
  firebase_messaging: ^14.6.4
  easy_localization: ^3.0.2
  auto_size_text: ^3.0.0
  onesignal_flutter: ^3.5.0
  device_info_plus: ^3.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/lang/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Cantarell.ttf
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Cantarell
      fonts:
        - asset: assets/fonts/Cantarell.ttf
  
  
  
  
  
  
  
  
  
  
  
  
  
