// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeUOBxfq0OetP3qHm5ij1ijxhDCVpmIU8',
    appId: '1:95384246442:web:79aeab4502a6e3f51cd8d3',
    messagingSenderId: '95384246442',
    projectId: 'copyoftwitter-5e905',
    authDomain: 'copyoftwitter-5e905.firebaseapp.com',
    storageBucket: 'copyoftwitter-5e905.appspot.com',
    measurementId: 'G-0NKFFBCS1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6a--2w8SECZTFOjwBn1I9VemUv2QgE4I',
    appId: '1:95384246442:android:9df18ec2caaabee01cd8d3',
    messagingSenderId: '95384246442',
    projectId: 'copyoftwitter-5e905',
    storageBucket: 'copyoftwitter-5e905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcZPp14espZivd5Fp6BraepIz8UB78fXQ',
    appId: '1:95384246442:ios:6ab0b2940e348f831cd8d3',
    messagingSenderId: '95384246442',
    projectId: 'copyoftwitter-5e905',
    storageBucket: 'copyoftwitter-5e905.appspot.com',
    androidClientId: '95384246442-sd921f7qd2occh9kcl2bekcl6hmdqbdb.apps.googleusercontent.com',
    iosClientId: '95384246442-tmsuf4f0plivl1i7qah8u4n2bmsjp07f.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcZPp14espZivd5Fp6BraepIz8UB78fXQ',
    appId: '1:95384246442:ios:6ab0b2940e348f831cd8d3',
    messagingSenderId: '95384246442',
    projectId: 'copyoftwitter-5e905',
    storageBucket: 'copyoftwitter-5e905.appspot.com',
    androidClientId: '95384246442-sd921f7qd2occh9kcl2bekcl6hmdqbdb.apps.googleusercontent.com',
    iosClientId: '95384246442-tmsuf4f0plivl1i7qah8u4n2bmsjp07f.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );
}
